# Generated by Django 5.1 on 2024-08-08 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_admin',
        ),
        migrations.RemoveField(
            model_name='tbl_place',
            name='district',
        ),
        migrations.RemoveField(
            model_name='tbl_local_place',
            name='place',
        ),
        migrations.DeleteModel(
            name='tbl_district',
        ),
        migrations.DeleteModel(
            name='tbl_local_place',
        ),
        migrations.DeleteModel(
            name='tbl_place',
        ),
    ]
